### ISSUE TITLE
Idempotency issue in EmployeePayrollUpdatesQueue function

### ISSUE THREAD

**Issue by NullPointer4096** [KyleMcMaster/payroll-processor#138]
**Description**
The EmployeePayrollUpdatesQueue function processes EmployeePayrollCreation and EmployeePayrollUpdate events in the queue. However, there is a potential idempotency issue that might cause duplicate processing of the events if the function is re-invoked with the same input.

**Steps to Reproduce**
1. Send an event to the AppResources.Queue.EmployeePayrollUpdates queue to trigger the function.
2. Have the function processing the event, updating or creating department payroll records.
3. Simulate an error after the HandleEmployeePayrollCreation (similar if you want to test api call but before the function returns for the function to fail.
4. Let the function automatically retry with the same message.

**Expected Behavior**
The EmployeePayrollUpdatesQueue function should be idempotent, ensuring that the same event is not processed multiple times, regardless of any exceptions, errors, or retries. Specifically in this case, we should not be updating or creating payroll records more than once.

**Actual Behavior**
If an error occurs during the execution of the function (as describe above), it may cause the function to be retried with the same input, leading to duplicate processing of the events and possibly updating or creating duplicate department payroll records.

**Suggested fix**
To ensure idempotency, implement a mechanism to track the state of the processed input message. This can be done by using Azure Table Storage or another storage service to store a unique identifier for each processed message. Before processing the input message, check if the unique identifier exists in the storage. If it does, skip processing the message, and if it doesn't, process the message and store the unique identifier in the storage. Additionally, consider implementing error handling and logging mechanisms to capture and handle any errors that occur during the processing of the events.

Thank you for your contribution to the Github community and I really appreciate your effort in following through this issue.

**Comment by KyleMcMaster** [comment]
Closing issue as this appears to be spam. If it is not, feel free to reopen and suggest meaningful changes to the codebase to fix the above concerns.
