### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by edmistond** [KyleMcMaster/payroll-processor#31]
Just for completeness' sake, you might consider applying an appropriate open source license to let people know it's okay to borrow some of these patterns, such as the AutoFixture/NSubstitute setup in PayrollProcessor.Tests.

I generally like MIT license, and it's what the dotnet runtime uses.

**Comment by KyleMcMaster** [comment]
Good idea! @seangwright Thoughts on this?

**Comment by seangwright** [comment]
Yup, good idea. I also use MIT https://opensource.org/licenses/MIT

**Comment by KyleMcMaster** [comment]
Marking issue as resolved after mergin PR #32
